name = "District 3"

# Supported pronounss: "He", "She", "They"
# avatar_url is currently a REQUIRED field, however it's currently not used.
[[tributes]]
name = "Tina"
avatar_url = "https://example.com/"
pronouns = "She"

[[tributes]]
name = "Regina"
avatar_url = "https://example.com/"
pronouns = "She"

[[tributes]]
name = "Sebrina"
avatar_url = "https://example.com/"
pronouns = "She"

[[tributes]]
name = "Katrina"
avatar_url = "https://example.com/"
pronouns = "She"
