name = "District 4"

# Supported pronounss: "He", "She", "They"
# avatar_url is currently a REQUIRED field, however it's currently not used.
[[tributes]]
name = "Aussie"
avatar_url = "https://example.com/"
pronouns = "They"

[[tributes]]
name = "Lossie"
avatar_url = "https://example.com/"
pronouns = "They"

[[tributes]]
name = "Bob"
avatar_url = "https://example.com/"
pronouns = "He"

[[tributes]]
name = "Lacrossie"
avatar_url = "https://example.com/"
pronouns = "They"
