name = "District 2"

# Supported pronounss: "He", "She", "They"
# avatar_url is currently a REQUIRED field, however it's currently not used.
[[tributes]]
name = "Amy"
avatar_url = "https://example.com/"
pronouns = "She"

[[tributes]]
name = "Andy"
avatar_url = "https://example.com/"
pronouns = "He"

[[tributes]]
name = "John"
avatar_url = "https://example.com/"
pronouns = "He"

[[tributes]]
name = "Gavin"
avatar_url = "https://example.com/"
pronouns = "He"
