# "killers", "killed", and "weight" are not required for events!!
# if they are not specified, "killers" and "killed" will default to
# none, and "weight" will default to 50

text = "(P1) runs away from the cornucopia. (They1) (P1)(doesn't/don't) know what to do so (they1) (P1)(is/are) running!"
category = "Bloodbath"
weight = 65
