# "killers", "killed", and "weight" are not required for events!!
# if they are not specified, "killers" and "killed" will default to
# none, and "weight" will default to 50

text = "(P1) eats (P2)."
category = "Day"
killed = [ "(P2)" ]
killers = [ "(P1)" ]
weight = 34
