# "killers", "killed", and "weight" are not required for events!!
# if they are not specified, "killers" and "killed" will default to
# none, and "weight" will default to 50

text = "(P1) fucking dies."
category = "Day"
killed = [ "(P1)" ]
weight = 20
