# "killers", "killed", and "weight" are not required for events!!
# if they are not specified, "killers" and "killed" will default to
# none, and "weight" will default to 50

text = "(P1) thinks about the time (they1) and (P2) got ice cream together."
category = "Day"
weight = 47
