# "killers", "killed", and "weight" are not required for events!!
# if they are not specified, "killers" and "killed" will default to
# none, and "weight" will default to 50

text = "(P1) takes a nap."
category = "Day"
weight = 24
